export const URL_ACCESS_MAP: Record<string, string[]> = {
  STUDENT: [
    "/courses",
    "/problems",
    "/dashboard",
    "/compiler",
    "/assessment",
    "/student-login",
    "/reset-password",
    "/problems",
    "/problem/:id",
    "/courses/:id/studyMode",
    "/courses/:id/assignment/:id/attempt",
    "/courses/:id/assignment/:assignmentId",
    "/courses/:id",
    "/courses",
    "/attempt",
    "/assessments/:id",
    "/assessments",
  ],

  VENDOR: [
    "/vendor-dashboard",
    "/reset-password",
    "/admin-dashboard/reports",
    "/admin-dashboard/institutions",
    "/admin-dashboard/vendors",
    "/admin-dashboard/vendors/:vendorId",
    "/admin-dashboard/reports",
    "/admin-dashboard/reports/courses/:id",
    "/admin-dashboard/reports/assessment/:id",
    "/admin-dashboard/problems",
    "/admin-dashboard/problems/:id",
    "/admin-dashboard/institutions",
    "/admin-dashboard/institutions/:institutionId",
    "/admin-dashboard/batches",
    "/admin-dashboard/batches/:batchId",
  ],

  INSTITUTION: [
    "/institution-dashboard",
    "/reset-password",
    "/admin-dashboard/reports",
    "/admin-dashboard/courses",
    "/admin-dashboard/batches",
    "/admin-dashboard/assessments",
    "/admin-dashboard/vendors",
    "/admin-dashboard/vendors/:vendorId",
    "/admin-dashboard/reports",
    "/admin-dashboard/reports/courses/:id",
    "/admin-dashboard/reports/assessment/:id",
    "/admin-dashboard/problems",
    "/admin-dashboard/problems/:id",
    "/admin-dashboard/institutions",
    "/admin-dashboard/institutions/:institutionId",
    "/admin-dashboard/batches",
    "/admin-dashboard/batches/:batchId",
    "/admin-dashboard/assessments",
    "/admin-dashboard/assessments/:id",
  ],

  TEACHER: [
    "/teacher-dashboard",
    "/reset-password",
    "/admin-dashboard/batches",
    "/admin-dashboard/batches/:batchId",
    "/admin-dashboard/reports",
  ],
  ADMIN: [
    "/admin-dashboard",
    "/admin-dashboard/admins",
    "/admin-dashboard/assessments",
    "/admin-dashboard/assessments/:id",
    "/admin-dashboard/vendors",
    "/admin-dashboard/vendors/:vendorId",
    "/admin-dashboard/reports",
    "/admin-dashboard/reports/courses/:id",
    "/admin-dashboard/reports/assessment/:id",
    "/admin-dashboard/problems",
    "/admin-dashboard/problems/:id",
    "/admin-dashboard/institutions",
    "/admin-dashboard/institutions/:institutionId",
    "/admin-dashboard/batches",
    "/admin-dashboard/batches/:batchId",
    "/admin-dashboard/courses",
    "/admin-dashboard/courses/:id",
  ]
};
