import { Router } from "express";
import dsaQuestionController from "../controller/dsa-question.controller";
import { authMiddleware as adminMiddleware } from "../middleware/auth.middleware";
const problemsRouter = Router();

problemsRouter.get(
  "/get-all-dsa-problem/",
  dsaQuestionController.getAllDsaProblem
);
problemsRouter.get(
  "/get-dsa-problem/:id/",
  dsaQuestionController.getDsaProblemById
);
problemsRouter.get(
  "/admin/get-dsa-problem/:id",
  adminMiddleware,
  dsaQuestionController.getAdminDsaProblemById
);
problemsRouter.get(
  "/admin/get-dsa-problem/testcases/:id",
  adminMiddleware,
  dsaQuestionController.getTestCaseById
);
problemsRouter.get(
  "/admin/get-dsa-problem/solution/:id",
  adminMiddleware,
  dsaQuestionController.getProblemSolutionById
);
problemsRouter.get(
  "/admin/get-dsa-problem/submission/:id",
  adminMiddleware,
  dsaQuestionController.getAllDsaSubmission
);
problemsRouter.get(
  "/admin/get-dsa-problem/templates/:id",
  adminMiddleware,
  dsaQuestionController.getTemplateById
);

problemsRouter.get(
  "/get-dsa-problems-by-tag",
  dsaQuestionController.getDsaProblemByTag
);
problemsRouter.post(
  "/add-problem/",
  adminMiddleware,
  dsaQuestionController.addDsaProblem
);
problemsRouter.patch(
  "/update-problem/:id",
  adminMiddleware,
  dsaQuestionController.updateDsaProblem
);
problemsRouter.delete(
  "/delete-problem/:id",
  adminMiddleware,
  dsaQuestionController.deleteDsaProblem
);
problemsRouter.post(
  "/add-topic-to-problem/:id",
  adminMiddleware,
  dsaQuestionController.addTopicToProblem
);
problemsRouter.patch(
  "/update-topic-to-problem/:id",
  adminMiddleware,
  dsaQuestionController.updateTopicToProblem
);
problemsRouter.delete(
  "/delete-topic-from-problem/:id",
  adminMiddleware,
  dsaQuestionController.deleteTopicFromProblem
);
problemsRouter.post(
  "/add-template-to-problem/:id",
  adminMiddleware,
  dsaQuestionController.addQuestionTemplate
);
problemsRouter.patch(
  "/update-template-to-problem/:id",
  adminMiddleware,
  dsaQuestionController.updateQuestionTemplate
);
problemsRouter.delete(
  "/delete-template-from-problem/:id",
  adminMiddleware,
  dsaQuestionController.deleteQuestionTemplate
);
problemsRouter.post(
  "/add-testcase-to-problem/:id",
  adminMiddleware,
  dsaQuestionController.addTestCaseToProblem
);
problemsRouter.patch(
  "/update-testcase-to-problem/:id",
  adminMiddleware,
  dsaQuestionController.updateTestCaseToProblem
);
problemsRouter.delete(
  "/delete-testcase-to-problem/:id",
  adminMiddleware,
  dsaQuestionController.deleteTestCaseToProblem
);
problemsRouter.post(
  "/add-solution-to-problem/:id",
  adminMiddleware,
  dsaQuestionController.addProblemSolution
);
problemsRouter.patch(
  "/update-solution-to-problem/:id",
  adminMiddleware,
  dsaQuestionController.updateProblemSolution
);
problemsRouter.delete(
  "/delete-solution-to-problem/:id",
  adminMiddleware,
  dsaQuestionController.removeProblemSolution
);
problemsRouter.get(
  "/get-user-solved-questions/",
  adminMiddleware,
  dsaQuestionController.getAllQuestionInfoById
);
problemsRouter.get(
  "/admin/get-user-solved-questions",
  adminMiddleware,
  dsaQuestionController.getAllQuestionInfo
);

export default problemsRouter;
